version: '3'
services:
  campaigns:
    image: python:3
    working_dir: /code
    ports:
      - 9000:5001
    volumes: 
      - ./services/campaigns:/code
    networks: 
      - mop_network
    depends_on:
      - mongo
      - mongo-express
    command: ["/bin/bash", "run.sh"]



#  front:
#    build: ./client
#    ports:
#      - 4200:4200
#    volumes:
#      - ./client:/front
#      - ./client/node_modules:/node_modules
#    command: ng serve --host=0.0.0.0
    # networks: 
    #   - mop_network

    
  resources:
    container_name: resources
    image: python:3
    working_dir: /code
    ports:
      - 9001:5000
    volumes:
      - ./services/resources:/code
    depends_on: 
      - mongo
      - mongo-express
    command: ["/bin/bash", "run.sh"]
    networks: 
      - mop_network
    
  mongo:
    image: mongo
    user: root
    ports:
      - "27017:27017"
    networks: 
      - mop_network


  mongo-express:
    image: mongo-express
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    networks: 
    - mop_network

networks: 
  mop_network:
    driver: bridge
