version: '3'
services:
  resources:
    build: ./services/resources
    ports:
      - 9001:5000
    volumes:
      - ./services/resources:/code
    command: /bin/sh ./run.sh

#
#  front:
#    build: ./client
#    ports:
#      - 4200:4200
#    volumes:
#      - ./client:/front
#      - ./client/node_modules:/node_modules
#    command: ng serve --host=0.0.0.0


  mongo:
    image: mongo
    user: root
    ports:
      - "27017:27017"

  mongo-express:
      image: mongo-express
      ports:
        - "8000:8081"
      environment:
        ME_CONFIG_BASICAUTH_USERNAME: root
        ME_CONFIG_BASICAUTH_PASSWORD: root
        ME_CONFIG_MONGODB_SERVER: mongo